
import type { Metadata } from "next";
import { Outfit, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/themesprovider"
import {SidebarProvider} from "@/components/ui/sidebar-provider";
import {ClerkProvider} from "@clerk/nextjs";


// Use Outfit as the default sans-serif font and expose it via a dedicated CSS variable
const outfitSans = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["300","400","500","600","700"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400","500","600","700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <>
            <ClerkProvider>
                <html lang="en" suppressHydrationWarning className={`${outfitSans.variable} ${geistMono.variable}`}>
                <head/>
                <body className="font-sans">
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
                </body>
                </html>
            </ClerkProvider>
        </>
    )
}